### ISSUE TITLE
Hard-coded Luma dependency causes endless spinner

### ISSUE THREAD

**Issue by LauHypershop** [MontaServices/magento-monta-checkout#102]
The problem is located in these lines:

vendor/monta/montacheckout/view/frontend/web/js/view/checkout/shipping/additional-block.js:915
```
const site_url = '/static/frontend/Magento/luma/nl_NL/Montapacking_MontaCheckout';
```

vendor/monta/montacheckout/view/frontend/web/js/view/checkout/shipping/additional-block.js:939
```
const site_url = '/static/frontend/Magento/luma/nl_NL/Montapacking_MontaCheckout';
```

If your theme does not descend from Luma (for example, from Blank, or a custom theme) or the locale is not nl_NL, this goes wrong when a customer clicks on the button to fetch additional pickup points. You get a loading spinner that spins forever, and in the console you get 404 errors.

**Comment by monta-kevinkroos** [comment]
Hi,

This issue has been resolved in version 1.1.17 where we build up the url dynamically instead of a hardcoded path.
